__version__: 27
Settings:
  Acquisitions:
    - Acquisition:
        Aperture: 2.83
        Brightness: 2
        ExposureTime: 2500
        Gain: 1
    - Acquisition:
        Aperture: 3.08
        Brightness: 2.5
        ExposureTime: 10000
        Gain: 1
  Color:
    __version__: 7
    Settings2D:
      Acquisitions:
        - Acquisition:
            Aperture: 2.83
            Brightness: 2.5
            ExposureTime: 2000
            Gain: 2
      Processing:
        Color:
          Balance:
            Blue: 1
            Green: 1
            Red: 1
          Experimental:
            Mode: automatic
          Gamma: 1
      Sampling:
        Color: rgb
        Pixel: all
  Diagnostics:
    Enabled: no
  Engine: sage
  Processing:
    Color:
      Balance:
        Blue: 1
        Green: 1
        Red: 1
      Experimental:
        Mode: automatic
      Gamma: 1
    Filters:
      Cluster:
        Removal:
          Enabled: yes
          MaxNeighborDistance: 3
          MinArea: 30
      Experimental:
        ContrastDistortion:
          Correction:
            Enabled: no
            Strength: 0.2
          Removal:
            Enabled: yes
            Threshold: 0.3
      Hole:
        Repair:
          Enabled: yes
          HoleSize: 0.1
          Strictness: 4
      Noise:
        Removal:
          Enabled: yes
          Threshold: 2
        Repair:
          Enabled: yes
        Suppression:
          Enabled: no
      Outlier:
        Removal:
          Enabled: yes
          Threshold: 5
      Reflection:
        Removal:
          Enabled: yes
          Mode: global
      Smoothing:
        Gaussian:
          Enabled: yes
          Sigma: 1
    Resampling:
      Mode: disabled
  RegionOfInterest:
    Box:
      Enabled: yes
      Extents: [0, 139.93274879455566]
      PointA: [186.505493, 183.919434, 597.251709]
      PointB: [-254.954468, -262.782928, 632.350952]
      PointO: [-267.511871, 162.943558, 555.331177]
    Depth:
      Enabled: no
      Range: [300, 1100]
  Sampling:
    Color: rgb
    Pixel: all
